apiVersion: apps/v1
kind: Deployment
metadata:
  name: webbot
  namespace: bots
  labels:
    app: webbot
    type: ishbot
spec:
  template:
    metadata:
      name: webbot-pod
      labels:
        app: webbot
        type: ishbot
    spec:
      containers:
        - name: webbot
          image: us-east4-docker.pkg.dev/ish-bot/ish-bot/ish_bot:7da6b7cdadbf30b8bcf612ca66178f6fdff772e2
          envFrom:
            - secretRef:
                name: ish-bot-proxy-auths
          ports:
            - containerPort: 5900
              name: vnc
          resources:
          volumeMounts:
          - name: storage
            mountPath: /ebs
          - name: config-volume
            mountPath: /app/configs

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: ish-bot-pvc
      - name: config-volume
        configMap:
          name: ish-bot-config

  replicas: 1
  selector:
    matchLabels:
      type: ishbot
