
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ish-bot-ebs-pvc
  namespace: bots
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ish-bot-ebs-sc
  resources:
    requests:
      storage: 2000Gi

# Switch to GlusterFS in the future