
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ish-bot-pvc
  namespace: bots
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ish-bot-sc
  resources:
    requests:
      storage: 220Gi

# Switch to GlusterFS in the future