apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 6DiPsiVmF+RbZIVriG3iY0xcshq35FRZ3tWBsU5hJJQ=
      - identity: {}

