apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: fXR/oSPPvG8z7hNmDzppzPXyKQ7BvFUTQ8KyMJVRHNc=
      - identity: {}

