apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 96aUGlQyJ7EvT1og4ItEkVGlW6d1ABMkT2jR/h/tU04=
      - identity: {}

