apiVersion: v1
kind: Pod
metadata:
  name: webbot-pod
  labels:
    name: webbot
    type: bot
spec:      
  containers:
  - name: ish-bot-container
    image: 127.0.0.1:12000/ish_bot
    ports:
      - containerPort: 5900
        name: vnc
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
